Write Hello World
chryssavarna/hello-world pull request #5
Opened 2018-02-18 16:32 UTC by chryssavarna

Ask for User Input

2018-02-18 16:51 UTC, Popcore requested changes

2018-02-18 16:51 UTC, Popcore commented on HelloWorld.py
> +text = input("Would you like to print Hello World? Y(yes) or N(No)")
`input` works well with python 3 but not really with python 2 - where `raw_input` is the way to take use inputs. I suggest to specify in you README file that this code requires python 3 in order to run.

2018-02-18 16:51 UTC, Popcore commented on HelloWorld.py
> +    pass
I'm unnecessarily strict here:  the message tells the user to either type "Y" or "N" but you are only handling the first case. Maybe add a message when a user press "N" or other keys?

2018-02-18 20:21 UTC, chryssavarna commented
@Popcore how does this look?

2018-02-19 10:22 UTC, Popcore approved these changes
Looks good. 

A possible improvement could be to make your functions a bit more flexible so that they can accept parameters and allow for reusability. I'm specifically thinking about the `AskQuestion` function. 
But the script does its job and works as expected so if you are happy with it go ahead and merge.

2019-08-28 17:15 UTC, merged

2019-08-28 19:38 UTC, Popcore commented
Yey 🎉

btw new year new github account. I am [here](https://github.com/ocramh) now